[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stunting-prediction-app"
version = "0.1.0"
description = "A Streamlit app for stunting prediction using TensorFlow Decision Forests."
authors = [{ name = "Your Name", email = "your.email@example.com" }]
dependencies = [
    "streamlit",
    "tensorflow",
    "tensorflow-decision-forests",
    "pandas",
    "numpy"
]

[tool.streamlit]
# (Optional) You can configure Streamlit specific settings here if needed
# server.headless = true
